jobs:
  build-deb:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Wrapper validation
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Speedup dpkg
      run: sudo sh -c "echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/force-unsafe-io"
    - continue-on-error: true
      name: Fix 'Setup Java' action Gradle caching
      run: 'sudo mkdir -p /tmp/fred-build/gradle

        sudo ln -s /tmp/fred-build/gradle ~/.gradle

        sudo chmod o+rwx ~/.gradle

        '
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt update

        sudo apt install build-essential debhelper devscripts equivs -y

        '
    - continue-on-error: true
      name: Install package build dependencies
      run: 'install_tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends
        --yes"

        sudo mk-build-deps --install -r --tool="${install_tool}" debian/control

        '
    - continue-on-error: true
      name: Build package
      run: 'sudo gbp buildpackage --git-ignore-branch --git-upstream-tag="HEAD" -us
        -uc --git-ignore-new || (EDITOR=true dpkg-source --commit . hack-1 && sudo
        gbp buildpackage --git-ignore-branch --git-upstream-tag="HEAD" -us -uc --git-ignore-new)

        '
    - continue-on-error: true
      name: Get package info
      run: 'dpkg -I ../freenet*.deb

        file ../freenet*.deb

        cp ../freenet*.deb ./

        '
    - continue-on-error: true
      name: Provide Debian Package
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        name: debian-package
        path: freenet_*.deb
    strategy:
      matrix:
        distribution:
        - temurin
        java:
        - 17
        os:
        - ubuntu-latest
name: Build debian package
on:
  repository_dispatch:
    types: trigger-ga___package.yml
